define({
    root : {
        countries: 'Countries',
        products: 'Products',
        year: 'Year',
        from_date: 'From Date',
        to_date: 'To Date',
        please_select: 'Please Select...',
        please_select_country: 'Please select one or more countries.',
        please_select_product: 'Please select a MODIS product.',
        please_select_year: 'Please select a year.',
        please_select_from_date: 'Please select the from date.',
        please_select_to_date: 'Please select the to date.',
        warning: 'Warning',
        nasa_warning: 'The requested service is temporarily unavailable. It is either overloaded or under maintenance. Please try later.',
        jan: 'Jan',
        feb: 'Feb',
        mar: 'Mar',
        apr: 'Apr',
        may: 'May',
        jun: 'Jun',
        jul: 'Jul',
        aug: 'Aug',
        sep: 'Sep',
        oct: 'Oct',
        nov: 'Nov',
        dec: 'Dec'
    },
    fr : true,
    es : true
});
